CREATE DATABASE employee_tracker;

USE employee_tracker;

CREATE TABLE department(
 id INTEGER UNSIGNED AUTO_INCREMENT  PRIMARY KEY,
 name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE role(
id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
title VARCHAR(30) UNIQUE NOT NULL,
salary DECIMAL UNSIGNED NOT NULL,
department_id INTEGER UNSIGNED NOT NULL,
FOREIGN KEY(department_id) REFERENCEs department(id)
);

CREATE TABLE employee(
id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INT UNSIGNED NOT NULL,
manager_id INT UNSIGNED,
FOREIGN KEY(manager_id) REFERENCES employee(id),
FOREIGN KEY(role_id) REFERENCES role(id)
);